# non end-to-end configuration
features:
    chords: ["chroma", "tonnetz"]
    rhythms: ["tempogram"]
    timbre: ["mfcc", "mfcc_delta", "mfcc_delta2"]
    emotions: ["static_arousal", "static_valence"]
    
experiment:
    batch_size: 64
    num_workers: 15
    log_freq: 50
model:
    
    seq_len: 32 # under 16kHz sampling rate
    # ==== make sure size is consistent with the one from dataloader ====
    sequential_input_size: 16
    # sequential_input_size: 12
    non_sequential_input_size: 3
    # ===================================================================
    hidden_size: 64
    layer_num: 4
    bidirectional: True
    ranking_weight: 0.5
    dropout_rate: 0
    use_ranking_loss: False

    use_lds: True
    use_fds: True
    lds_ks: 5
    lds_sigma: 2
    bin_size: 0.05
    bucket_num: 20


hparas:              
    sr: 16000                     # Experiment hyper-parameters
    valid_step: 1000
    curriculum: 0
    max_epoch: 1000
    max_step: 15001
    tf_start: 1.0
    tf_end: 1.0
    tf_step: 500000
    grad_clip: 'inf'
    optimizer:
        type: 'Adam'
        lr: 0.0005
    lr_scheduler:
        type: 'warmup'                   # 'fixed'/'warmup'/'decay'/'reduce_lr_on_plateau'
    # freq_loss_type: 'l1'                         # 'l1'/'mse'
    # differential_loss: False
    # emphasize_linear_low: False

    lds_ks: 5
    lds_sigma: 2
    bin_size: 0.05

path:
    data_file: "data/data.csv"
    chroma_dir: "data/1_second_features/chroma/"
    timbre_dir: "data/1_second_features/timbre/"
    source_separated_dir: "/media/lab812/53D8AD2D1917B29C/AudMem/dataset/sources_separated/"

    features_dir: "data/features"
    label_file: "data/labels/track_memorability_scores_beta.csv"