# non end-to-end configuration
features:
    chords: ["chroma"]
    rhythms: ["tempogram"]
    timbre: ["mfcc"]
    emotions: ["static_arousal", "static_valence"]
    
experiment:
    batch_size: 64
    epochs: 100

model:
      # ==== make sure size is consistent with the one from dataloader ====
    sequential_input_size: 24
    non_sequential_input_size: 2
    # ===================================================================
    
    hidden_size: 100
    learning_rate: 0.0005
path:
    features_dir: "data/features"
    labels_dir: "data/labels"