# non end-to-end configuration
features:
    chords: ["chroma"]
    rhythms: ["tempogram"]
    timbre: ["mfcc"]
    emotions: ["static_arousal", "static_valence"]
    
experiment:
    batch_size: 64
    num_workers: 15

model:
    seq_len: 157 # under 16kHz sampling rate
    # ==== make sure size is consistent with the one from dataloader ====
    sequential_input_size: 416
    # sequential_input_size: 32
    non_sequential_input_size: 2
    # ===================================================================
    hidden_size: 100
    layer_num: 4
    bidirectional: True
    ranking_weight: 0.5

hparas:                                   # Experiment hyper-parameters
    valid_step: 1000
    curriculum: 0
    max_epoch: 100
    max_step: 15001
    tf_start: 1.0
    tf_end: 1.0
    tf_step: 500000
    grad_clip: 'inf'
    optimizer:
        type: 'Adam'
        lr: 0.001
    lr_scheduler:
        type: 'warmup'                   # 'fixed'/'warmup'/'decay'/'reduce_lr_on_plateau'
    freq_loss_type: 'l1'                         # 'l1'/'mse'
    differential_loss: False
    emphasize_linear_low: False

path:
    features_dir: "data/features"
    labels_dir: "data/labels"