features:
    chords: ["chroma"]
    rhythms: ["tempogram"]
    timbre: ["mfcc"]
    emotions: ["static_arousal", "static_valence"]
experiment:
    batch_size: 128
    epochs: 100
    learning_rate: 0.0005
model:
    seq_len: 157 # under 16kHz sampling rate
    # need to sync with memorability model config
    input_size: 200
    layer_num: 4 
    output_size: 128 #librosa n_mels
    downsampling_factor: 4
path:
    features_dir: "data/features"
    hidden_states_dir: "data/hidden_states"
    labels_dir: "data/labels"