experiment:
    batch_size: 128
    epochs: 1
    learning_rate: 0.01
model:
    input_size: 640
    layer_num: 4 
    output_size: 128 #librosa n_mels
path:
    features_dir: "data/features"
    hidden_states_dir: "data/hidden_states"
    labels_dir: "data/labels"